spring:
  datasource:
    main:
      url: jdbc:mysql://127.0.0.1:3306/main?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&tinyInt1isBit=false&useSSL=false
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 100
      maxActive: 1000
      minIdle: 100
      poolPreparedStatements: false
    slave:
      url: jdbc:mysql://127.0.0.1:3306/slave?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&tinyInt1isBit=false&useSSL=false
      username: root
      password: 123456
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 100
      maxActive: 1000
      minIdle: 100
      poolPreparedStatements: false
  transaction:
    rollback-on-commit-failure: true
  jackson:
    default-property-inclusion: non_null
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:logback.xml
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true


