spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/second_kill?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&tinyInt1isBit=false&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 100
      max-active: 1000
      min-idle: 100
      pool-prepared-statements: true
  transaction:
    rollback-on-commit-failure: true
  jackson:
    default-property-inclusion: non_null
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:logback.xml
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true


